### ISSUE TITLE
Cached scene dependency data makes addressables build significantly slower.

### ISSUE THREAD

**Issue by Sambo3975** [juniordiscart/com.unity.addressables#11]
For some reason, the cached scene dependency data slows the build down to an absolute crawl.

Expected Behavior: Cached data makes the build faster when present.
Actual Behavior: When cached data is present, the build takes upward of 10 minutes. If I clear the cached data, the build takes about 15 seconds.

**Comment by juniordiscart** [comment]
Hi

I assume this is an issue in the Scriptable Build Pipeline, which is talked about in this thread: https://forum.unity.com/threads/building-addressables-with-cached-elements-using-scriptablebuildpipeline-1-21-21-extremely-slow.1512488/

Since it's in a different package, this won't be fixed this until the Addressables team pushes an update on SBP.

**Comment by juniordiscart** [comment]
I think the best scenario is to switch back to a previous version of Addressables, which rolls back the version of the Scriptable Build Pipeline. Otherwise, if you want to stay on this version, you can create a small custom build script that clears the cache before building.

**Comment by Sambo3975** [comment]
OK. Thanks.

I'll just close this since it's an issue with a separate package.
